### ISSUE TITLE
Add wallet info to main screen - from restless on bitcointalk

### ISSUE THREAD

**Issue by airwalker1** [nemosminer/NemosMiner-v2.4.2#153]
A small addon:

Changing lines in main ps1 file from
Code:
#Display mining information
    Clear-Host
    Write-Host "1BTC = " $Rates.$Currency "$Currency"

to
Code:

  $Balance = Invoke-RestMethod "https://www.ahashpool.com/api/wallet/?address=$Wallet"
   $usd = $rates.$Currency
   $money= $Balance.balance*$usd
  #Display mining information
   Clear-Host
   Write-Host "1BTC = " $Rates.$Currency "$Currency"
   write-host "Wallet Balance:"$Balance.balance "BTC which is approximately " $Money "USD"
We'll get on top of screen something like:
Quote
1BTC =  15139.78 USD
Wallet Balance: 0.00270011 BTC which is approximately  40.8790713758 USD

**Comment by mullen1200** [comment]
Thanks, I just had to tab over the last 2 lines after I pasted and it worked.

**Comment by mullen1200** [comment]
I got an answer from Ahashpool on whether this is safe and if they ban users that call the API too much.

-----------------------------------------------------
It is ok to call it once every 10 minutes.  We only update the stats every 10 minutes anyway, so calling it more frequent would not give any benefit.

Because we have well over 5000 users now, anything more frequent would amount to DDoS attack on the server and everyone would suffer

**Comment by Teqqles** [comment]
Do they rate limit the API in a way that can be checked for in code so backoff can be implemented if this becomes a problem?

**Comment by Alex735566** [comment]
@airwalker1 You can read more in which file and at what place you want to add and that?

**Comment by nemosminer** [comment]
added profit tracking
